config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'vitamins#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :vitamins, only: %i[index show] do
    resources :activities, only: %i[new create]
    resources :food_intakes, only: %i[new create]
    resources :daily_vitamins, only: %i[index show], module: :vitamins
  end
end

app/models/activity.rb
# frozen_string_literal: true

class Activity < ApplicationRecord
  belongs_to :daily_vitamin

  validates :value, presence: true, numericality: { greater_than_or_equal_to: 1, less_than_or_equal_to: 3, only_integer: true }
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/daily_vitamin.rb
# frozen_string_literal: true

class DailyVitamin < ApplicationRecord
  belongs_to :user
  belongs_to :vitamin
  has_many :activities, dependent: :destroy
  has_many :food_intakes, dependent: :destroy

  validates :total, numericality: { less_than_or_equal_to: 10, only_integer: true }
end

app/models/food_intake.rb
# frozen_string_literal: true

class FoodIntake < ApplicationRecord
  belongs_to :daily_vitamin

  validates :value, presence: true, numericality: { greater_than_or_equal_to: 4, less_than_or_equal_to: 10, only_integer: true }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :daily_vitamins, dependent: :destroy
end

app/models/vitamin.rb
# frozen_string_literal: true

class Vitamin < ApplicationRecord
  validates :name, presence: true, uniqueness: true
end

app/controllers/activities_controller.rb
# frozen_string_literal: true

class ActivitiesController < ApplicationController
  before_action :set_vitamin
  respond_to :html

  def new
    @activity = Activity.new
  end

  def create
    @vitamin_control = VitaminControlService.new(current_user, @vitamin, activity_params)
    @activity = @vitamin_control.perform_activity
    if @activity.persisted?
      redirect_to vitamin_daily_vitamin_path(@vitamin, @activity.daily_vitamin)
    else
      render :new
    end
  end

  private

  def set_vitamin
    @vitamin = Vitamin.find(params[:vitamin_id])
  end

  def activity_params
    params.require(:activity).permit(:value)
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/food_intakes_controller.rb
# frozen_string_literal: true

class FoodIntakesController < ApplicationController
  before_action :set_vitamin
  respond_to :html

  def new
    @food_intake = FoodIntake.new
  end

  def create
    @vitamin_control = VitaminControlService.new(current_user, @vitamin, food_intake_params)
    @food_intake = @vitamin_control.perform_food_intake
    if @food_intake.persisted?
      redirect_to vitamin_daily_vitamin_path(@vitamin, @food_intake.daily_vitamin)
    else
      render :new
    end
  end

  private

  def set_vitamin
    @vitamin = Vitamin.find(params[:vitamin_id])
  end

  def food_intake_params
    params.require(:food_intake).permit(:value)
  end
end

app/controllers/vitamins/daily_vitamins_controller.rb
# frozen_string_literal: true

module Vitamins
  class DailyVitaminsController < ApplicationController
    before_action :find_vitamin

    def index
      @daily_vitamins = current_user.daily_vitamins.where(vitamin: @vitamin)
    end

    def show
      @daily_vitamin = current_user.daily_vitamins.find(params[:id])
    end

    private

    def find_vitamin
      @vitamin = Vitamin.find(params[:vitamin_id])
    end
  end
end

app/controllers/vitamins_controller.rb
# frozen_string_literal: true


class VitaminsController < ApplicationController
  def index
    @vitamins = Vitamin.all
  end

  def show
    @vitamin = Vitamin.find(params[:id])
    @daily_vitamins = current_user.daily_vitamins.where(vitamin_id: @vitamin)
  end
end

app/helpers/activities_helper.rb
module ActivitiesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/daily_vitamins_helper.rb
module DailyVitaminsHelper
end

app/helpers/food_intakes_helper.rb
module FoodIntakesHelper
end

app/helpers/vitamins_helper.rb
module VitaminsHelper
end

app/views/activities/new.html.erb
<%= simple_form_for([@vitamin, @activity]) do |f| %>
  <%= f.input :value %>
  <%= f.button :submit %>
<% end %>

app/views/food_intakes/new.html.erb
<%= simple_form_for([@vitamin, @food_intake]) do |f| %>
  <%= f.input :value %>
  <%= f.button :submit %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>VitaminControl</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/shared/_vitamin_links.html.erb
<%= link_to 'Add Activity', new_vitamin_activity_path(@vitamin) %>
<br>
<%= link_to 'Add Food Intake', new_vitamin_food_intake_path(@vitamin) %>

app/views/vitamins/daily_vitamins/_activity.html.erb
<br>
Value: <%= activity.value %>

app/views/vitamins/daily_vitamins/_food_intake.html.erb
<br>
Value: <%= food_intake.value %>

app/views/vitamins/daily_vitamins/index.html.erb
<% @daily_vitamins.each do |daily_vitamin| %>
  <p>Vitamin: <%= daily_vitamin.name %></p>
  <p>Day: <%= daily_vitamin.created_at.strftime("%Y-%m-%d") %></p>
<% end %>

app/views/vitamins/daily_vitamins/show.html.erb
<%= render 'shared/vitamin_links' %>
<br>
Current Level: <%= @daily_vitamin.total %>
<br>
Activities:
<%= render partial: 'activity', collection: @daily_vitamin.activities, as: :activity %>
<br>
<br>
Food Intakes:
<%= render partial: 'food_intake', collection: @daily_vitamin.food_intakes, as: :food_intake %>

app/views/vitamins/index.html.erb
<% @vitamins.each do |vitamin| %>
  <p><%= link_to vitamin.name, vitamin %></p>
<% end %>

app/views/vitamins/show.html.erb
<%= render 'shared/vitamin_links' %>
<% if @daily_vitamins.present? %>
  <table>
    <thead>
      <th>Vitamin</th>
      <th>Day</th>
      <th>Current Level</th>
    </thead>
    <tbody>
      <% @daily_vitamins.each do |daily_vitamin| %>
        <tr>
          <td><%= link_to @vitamin.name, vitamin_daily_vitamin_path(@vitamin, daily_vitamin) %></td>
          <td><%= daily_vitamin.created_at.strftime("%Y-%m-%d") %></td>
          <td><%= daily_vitamin.total %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% end %>